//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;

public class MyPanel extends JPanel {
    private JLabel jcomp1;
    private JCheckBox jcomp2;
    private JCheckBox jcomp3;
    private JCheckBox jcomp4;
    private JLabel jcomp5;
    private JCheckBox jcomp6;
    private JCheckBox jcomp7;
    private JCheckBox jcomp8;
    private JCheckBox jcomp9;
    private JCheckBox jcomp10;
    private JCheckBox jcomp11;
    private JComboBox jcomp12;
    private JToggleButton jcomp13;

    public MyPanel() {
        //construct preComponents
        String[] jcomp12Items = {"전체", "이름", "번호", "생일", "성별", "월급", "상사", "부서"};

        //construct components
        jcomp1 = new JLabel ("검색 범위");
        jcomp2 = new JCheckBox ("전체");
        jcomp3 = new JCheckBox ("Name");
        jcomp4 = new JCheckBox ("Ssn");
        jcomp5 = new JLabel ("검색 항목");
        jcomp6 = new JCheckBox ("Bdate");
        jcomp7 = new JCheckBox ("Address");
        jcomp8 = new JCheckBox ("Sex");
        jcomp9 = new JCheckBox ("Salary");
        jcomp10 = new JCheckBox ("Supervisor");
        jcomp11 = new JCheckBox ("Department");
        jcomp12 = new JComboBox (jcomp12Items);
        jcomp13 = new JToggleButton ("검색", false);

        //adjust size and set layout
        setPreferredSize (new Dimension (796, 427));
        setLayout (null);

        //add components
        add (jcomp1);
        add (jcomp2);
        add (jcomp3);
        add (jcomp4);
        add (jcomp5);
        add (jcomp6);
        add (jcomp7);
        add (jcomp8);
        add (jcomp9);
        add (jcomp10);
        add (jcomp11);
        add (jcomp12);
        add (jcomp13);

        //set component bounds (only needed by Absolute Positioning)
        jcomp1.setBounds (20, 20, 60, 25);
        jcomp2.setBounds (80, 45, 50, 25);
        jcomp3.setBounds (130, 50, 60, 15);
        jcomp4.setBounds (190, 45, 50, 25);
        jcomp5.setBounds (20, 45, 100, 25);
        jcomp6.setBounds (240, 45, 65, 25);
        jcomp7.setBounds (305, 45, 80, 25);
        jcomp8.setBounds (390, 45, 50, 25);
        jcomp9.setBounds (445, 45, 70, 25);
        jcomp10.setBounds (515, 45, 100, 25);
        jcomp11.setBounds (615, 45, 100, 25);
        jcomp12.setBounds (80, 20, 100, 25);
        jcomp13.setBounds (725, 45, 70, 25);
    }


    public static void main (String[] args) {
        JFrame frame = new JFrame ("MyPanel");
        frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().add (new MyPanel());
        frame.pack();
        frame.setVisible (true);
    }
}
